import "reflect-metadata";
import cookie from "@fastify/cookie";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import dotenv from "dotenv";
import rateLimit from "@fastify/rate-limit";
dotenv.config();

//for testing
import swagger from "@fastify/swagger";
import swaggerUI from "@fastify/swagger-ui";

import Fastify from "fastify";
import { AppDataSource } from "./data-source";
import { userRoutes } from "./api/v1/user";
import { authRoutes } from "./api/v1/auth";
import { getEnv } from "./data-source";
import authPlugin from "./plugin/authenticate";

const fastify = Fastify({
    logger: true
});

async function start() {

    await AppDataSource.initialize();

    await fastify.register(cookie, {
        secret: getEnv("COOKIE_SECRET"),
    });

    console.log("Database connected");

    // If the error is related to CORS, you can try adding the following code to your Fastify server setup to enable CORS and allow requests from your frontend application:
    await fastify.register(cors, {
        origin: ["http://localhost:5174", "http://localhost:8081", "http://localhost:3000", "http://localhost:5173"],
        credentials: true,
    });

    //cần sửa trong tương lai ----------------------------------------------------- set to be true
    await fastify.register(helmet, {
        contentSecurityPolicy: false,
    });
    // 
    await fastify.register(rateLimit, {
        max: 50,
        timeWindow: "1 minute",
    });
    await fastify.register(swagger, {
        openapi: {
            info: {
                title: "COMP.SEC.300 Secure API",
                description: "Secure CRUD API with authentication for user management",
                version: "1.0.0",
            },
            servers: [
                {
                    url: "http://localhost:8081",
                },
            ],
            components: {
                securitySchemes: {
                    cookieAuth: {
                        type: "apiKey",
                        in: "cookie",
                        name: "token",
                    },
                },
            },
        },
    });
    // This registers the Swagger UI plugin, which provides an interactive interface for exploring and testing the API documentation generated by the Swagger plugin. By accessing the "/documentation" route, you can view the API endpoints, their expected inputs and outputs, and even make test requests directly from the browser. This is a valuable tool for developers to understand how to interact with the API and to verify that it behaves as expected.
    await fastify.register(swaggerUI, {
        routePrefix: "/documentation",
    });
    // This registers the authentication plugin, which adds an "authenticate" decorator to the Fastify instance. This decorator can be used as a pre-handler for routes that require authentication. It checks for a signed cookie containing a JWT token, verifies the token, and attaches the decoded payload to the request object. If the token is missing, invalid, or has an invalid signature, it responds with a 401 error. This plugin is essential for protecting routes and ensuring that only authenticated users can access certain resources.
    await fastify.register(authPlugin);
    // This registers the authentication routes, which include endpoints for logging in, logging out, and retrieving the currently authenticated user's information. These routes handle user authentication and session management using JWT tokens stored in cookies. Try accessing these routes to see how the authentication mechanism works and to test the login and logout functionality.
    await fastify.register(authRoutes);
    // This registers the user routes, which include endpoints for retrieving all users and retrieving a user by their UUID. These routes are protected by authentication, meaning that you must be logged in to access them. Try accessing these routes without logging in to see the 401 error, then log in and access them again to see the user information returned. This tests the authentication mechanism and ensures that only authenticated users can access this sensitive information.
    await fastify.register(userRoutes);


    fastify.get("/", async () => {
        return { message: "API running" };
    });

    await fastify.listen({ port: 8081, host: "0.0.0.0" });
}

start().catch((err) => {
    console.error(err);
    process.exit(1);
});